steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['GOPATH=.']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', 'container-builder-local']
  env: ['GOPATH=.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/container-builder-local', '.']

images: ['gcr.io/$PROJECT_ID/container-builder-local']
