# This build is triggered on push to the release branch in order to ensure that
# code compiles prior to creating a Pull Request to the master branch.

steps:
# Run unit tests in all subdirectories (except those excluded by the grep).
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration_tests" | xargs /builder/bin/go.bash test

# Binary creation.
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['build', '-o', 'container-builder-local', 'github.com/GoogleCloudPlatform/container-builder-local']

# Copy the integration test files to GCS.

- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil rm gs://container-builder-local-test-logs/*

# Copy the integration test files to GCS and
# run integration tests in a VM.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    DATE=`date +%Y%m%d_%H%M%S`
    GCS_PATH=gs://container-builder-local-test/$$DATE
    gsutil -m copy container-builder-local $$GCS_PATH/
    gsutil -m copy ./integration_tests/* $$GCS_PATH/
    gsutil rm gs://container-builder-local-test-logs/*

    gcloud config set compute/zone us-central1-f
    gcloud compute instances create ubuntu-integration-tests \
      --image-family=ubuntu-1404-lts \
      --image-project=ubuntu-os-cloud \
      --machine-type=n1-standard-4 \
      --scopes default,userinfo-email,useraccounts-ro,cloud-platform \
      --metadata-from-file startup-script=integration_tests/gce_startup_script.sh \
      --metadata zone=us-central1-f,gcs_path=$$GCS_PATH

    # Wait until either the success or failure file is written to GCS.
    status=0
    while true
    do
      if gsutil stat gs://container-builder-local-test-logs/success.txt 2> /dev/null; then
        gsutil cat gs://container-builder-local-test-logs/success.txt
        break
      fi
      if gsutil stat gs://container-builder-local-test-logs/failure.txt 2> /dev/null; then
        gsutil cat gs://container-builder-local-test-logs/failure.txt
        status=1
        break
      fi
      echo "Tests are still running, checking in a few seconds..."
      sleep 5
    done

    # Delete the VM and return the status
    #gcloud compute instances delete ubuntu-integration-tests --quiet
    exit $status


