# This build is triggered on push to the release branch in order to ensure that
# code compiles prior to creating a Pull Request to the master branch.

steps:
# Run unit tests in all subdirectories (except those excluded by the grep).
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration_tests" | xargs /builder/bin/go.bash test

# Binary creation.
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['build', '-o', 'container-builder-local', 'github.com/GoogleCloudPlatform/container-builder-local']

# Copy the integration test files to GCS.

- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil rm gs://container-builder-local-test/*
    gsutil rm gs://container-builder-local-test-logs/*
    gsutil copy container-builder-local gs://container-builder-local-test/
    gsutil copy ./integration_tests/* gs://container-builder-local-test/

# Run integration tests in a VM.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute instances create ubuntu-integration-tests \
      --image-family=ubuntu-1404-lts \
      --image-project=ubuntu-os-cloud \
      --machine-type=n1-standard-1 \
      --scopes userinfo-email,cloud-platform \
      --metadata-from-file startup-script=integration_tests/gce_startup_script.sh \
      --zone us-central1-f \
      --metadata zone=us-central1-f

    # Wait until either the success or failure file is written to GCS.
    status=0
    while true
    do
      if gsutil stat gs://container-builder-local-test-logs/success.txt; then
        gsutil cat gs://container-builder-local-test-logs/success.txt
        break
      fi
      if gsutil stat gs://container-builder-local-test-logs/failure.txt; then
        gsutil cat gs://container-builder-local-test-logs/failure.txt
        status=1
        break
      fi
      echo "tests not finished yet, checking in a few seconds"
      sleep 2
    done

    # Delete the VM and return the status
    gcloud compute instances delete ubuntu-integration-tests --quiet
    return status


