# This build is triggered on push to the release branch in order to ensure that
# code compiles prior to creating a Pull Request to the master branch.
steps:
# Run unit tests in all subdirectories (except those excluded by the grep).
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration_tests" | xargs /builder/bin/go.bash test

# Binary creation.
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['build', '-o', 'container-builder-local', 'github.com/GoogleCloudPlatform/container-builder-local']

# Create a docker image with all the tools needed to test the local builder.
# The lastest image is pulled first in order to make the next build faster,
# using --cache-from.
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['pull', 'gcr.io/argo-local-builder/integration-image']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--cache-from'
  - 'gcr.io/argo-local-builder/integration-image'
  - '-t'
  - 'gcr.io/argo-local-builder/integration-image'
  - './integration_tests/.'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/argo-local-builder/integration-image']

# Run integration tests.
- name: 'gcr.io/argo-local-builder/integration-image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker images
    cp container-builder-local /usr/local/bin/
    go test ./integration_tests/smoke_test.go \
     --files_path=$$PWD/integration_tests/



# This image is saved to make subsequent build faster if the tools didn't change.
images: ['gcr.io/argo-local-builder/integration-image']
