steps:
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['install', 'github.com/GoogleCloudPlatform/container-builder-local']
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['test', 'github.com/GoogleCloudPlatform/container-builder-local/...']
- name: 'busybox'
  args: ['ls', './gopath/bin']
