steps:
- name: 'busybox'
  args: ['pwd']
- name: 'busybox'
  args: ['ls']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=container-builder-local']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', 'container-builder-local']
  env: ['PROJECT_ROOT=container-builder-local']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/container-builder-local', '.']

images: ['gcr.io/$PROJECT_ID/container-builder-local']
