steps:
- name: 'busybox'
  args: ['mkdir', '-p', 'src/container-builder-local']
- name: 'busybox'
  args: ['ls', 'src/']
# don't use busybox which fails with mv.
- name: 'debian'
  args: ['cp', '*', 'src/container-builder-local/']
- name: 'gcr.io/cloud-builders/go'
  args:
  - 'get'
  - 'golang.org/x/oauth2'
  - 'github.com/google/uuid'
  - 'gopkg.in/yaml.v2'
  - 'google.golang.org/api/cloudkms/v1'
  - 'google.golang.org/api/cloudbuild/v1'
  env: ['GOPATH=.']
- name: 'busybox'
  args: ['pwd']
- name: 'busybox'
  args: ['ls', '.']
- name: 'busybox'
  args: ['ls', 'src/']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'container-builder-local']
  env: ['GOPATH=.']
- name: 'busybox'
  args: ['ls', 'pkg/']
- name: 'busybox'
  args: ['ls', 'bin']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', '...']
  env: ['GOPATH=.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/container-builder-local', '.']

images: ['gcr.io/$PROJECT_ID/container-builder-local']
