steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'github.com/GoogleCloudPlatform/container-builder-local']
- name: 'gcr.io/cloud-builders/go'
  args: ['list', './...']
- name: 'gcr.io/cloud-builders/go'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    go test $(go list ./... | grep -v /vendor/)
- name: 'busybox'
  args: ['ls', './gopath/bin']
