steps:
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['install', 'github.com/GoogleCloudPlatform/container-builder-local']
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    go list ./... | grep -v /vendor/
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['test', './runner']
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    go test $(ls -d */ | grep -v vendor)
- name: 'busybox'
  args: ['ls', './gopath/bin']
