# This build is triggered on push to the release branch in order to ensure that
# code compiles prior to creating a Pull Request to the master branch.
steps:
# Run unit tests in all subdirectories (except those excluded by the grep).
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath" | xargs /builder/bin/go.bash test
# Binary creation.
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['build', '-o', 'container-builder-local', 'github.com/GoogleCloudPlatform/container-builder-local']

