steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'github.com/GoogleCloudPlatform/container-builder-local']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...']
- name: 'busybox'
  args: ['ls', './gopath/bin']
