steps:
- name: 'gcr.io/cloud-builders/go:wheezy'
  args: ['install', 'github.com/GoogleCloudPlatform/container-builder-local']
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # go test .
    for dir in */
    do
      package=./${dir%/}
      echo ${package}
      # go test ${package}
    done
    # find . -type d -maxdepth 1 | grep -Ev "vendor|.git" | xargs go test
- name: 'busybox'
  args: ['ls', './gopath/bin']
