# This build happens when a new tag is created, the goal being to create all the
# binaries and copy them to GCS.
steps:
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration-test" | xargs /builder/bin/go.bash test
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for GOOS in darwin linux windows; do
        for GOARCH in 386 amd64; do
            /builder/bin/go.bash build -o -v container-builder-local_$${GOOS}_$${GOARCH}-$TAG_NAME github.com/GoogleCloudPlatform/container-builder-local
        done
    done
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'container-builder-local_*', 'gs://container-builder-local/']
