# This build is triggered when a new tag is created in order to compile
# binaries and copy them to GCS.
steps:
# Run unit tests in all subdirectories (except those excluded by the grep).
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration_tests" | xargs /builder/bin/go.bash test
# Set TAG_NAME as version.
- name: 'ubuntu'
  args: ['sed', '-i', 's/HEAD/$TAG_NAME/g', 'version.go']
# Create binaries.
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for GOOS in darwin linux windows; do
        for GOARCH in 386 amd64; do
            # Build binary with the new tag and with 'latest'
            GOOS=$$GOOS GOARCH=$$GOARCH /builder/bin/go.bash build -o container-builder-local_$${GOOS}_$${GOARCH}-$TAG_NAME github.com/GoogleCloudPlatform/container-builder-local
            GOOS=$$GOOS GOARCH=$$GOARCH /builder/bin/go.bash build -o container-builder-local_$${GOOS}_$${GOARCH}-latest github.com/GoogleCloudPlatform/container-builder-local
        done
    done
# Copy binaries to GCS.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', 'container-builder-local_*', 'gs://container-builder-local/']
