# This build happens on push to the release branch, the goal being to check
# the code compiles before manually creating a Pull Request to the master branch.
steps:
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration-test" | xargs /builder/bin/go.bash test
#- name: 'gcr.io/cloud-builders/go:wheezy'
#  args: ['install', 'github.com/GoogleCloudPlatform/container-builder-local']
- name: 'gcr.io/cloud-builders/go:wheezy'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for GOOS in darwin linux windows; do
        for GOARCH in 386 amd64; do
            echo Building binary for $$GOOS-$$GOARCH
            /builder/bin/go.bash build -o container-builder-local_$${GOOS}_$${GOARCH}-$COMMIT_SHA github.com/GoogleCloudPlatform/container-builder-local
        done
    done
    GOOS=darwin GOARCH=386 /builder/bin/go.bash build -o container-builder-local_yo github.com/GoogleCloudPlatform/container-builder-local
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update || exit
    apt-get install -y file || exit
    file container-builder-local_*
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'container-builder-local_*', 'gs://container-builder-local/']

- name: 'busybox'
  args: ['echo', 'Create a Github PR from release to master branch.']
